export const PAGINATION = {
  PAGE_LIMIT: 10,
  OPTIONAL_PAGE_LIMIT: 5,
  ROWS_PER_PAGE_OPTIONS: [1, 5, 10, 15, 20],
  CURRENT_PAGE: 1,
  PAGE_COUNT: 1,
  TOTAL_RECORDS: 0,
  DROPDOWNS_RECORD_LIMIT: 50,
};
