import { ATTACHMENT_FILE_TYPE } from "./file";

export const FILE_TYPE_BASED_IMAGES = {
  [ATTACHMENT_FILE_TYPE?.PDF]: { src: "" },
  [ATTACHMENT_FILE_TYPE?.XLS]: { src: "" },
  [ATTACHMENT_FILE_TYPE?.CSV]: { src: "" },
  [ATTACHMENT_FILE_TYPE?.DOC]: { src: "" },
  [ATTACHMENT_FILE_TYPE?.DOCX]: { src: "" },
};

export const STATIC_BLUR_DATA_URL = `data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAIAAAD8JczVAAAAmklEQVRIDbXBAQEAAAABIP6PzgpV8OQe84F0pKCW4GEHzpRZ7lBCBXbgTkQ4q0U9yswFtr9XlDPX0WoSzAkFqgg2eORl35A0wT2AM5Xj0cYw51TbdTA0vTpDbYfmsd2bGSB4vFQzzbxDLcRg4uAvwFAAAA//8DAIaJeYcAAAAASUVORK5CYII=
`;
