import type { Metadata } from "next";
import { DM_Sans } from "next/font/google";
import "./globals.css";
import { UiThemeProvider } from "@/providers/ui-theme-provider";
import { SnackBarProvider } from "@/providers/snackbar.provider";

const dmSans = DM_Sans({
  subsets: ["latin"],
  weight: ["100", "400", "500", "600", "700", "800", "900"],
  display: 'swap',
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${dmSans.className}`}>
        <UiThemeProvider>
          <SnackBarProvider>{children}</SnackBarProvider>
        </UiThemeProvider>
      </body>
    </html>
  );
}
